### ISSUE TITLE
Path Issue

### ISSUE THREAD

**Issue by adaza** [kiritmodi2702/GIFIamgeView_Swift#1]
This may be the noobiest question ever. I having only been doing Xcode and Swift for a few weeks and this extension is exactly what I am looking for as I learn Swift.  However:

1) When I try to compile SwiftGIFImage.xcodeproj (toward the simulator), it gives the error:
"bridging header '/Users/mspsys087/Desktop/SwiftGIFImage/SwiftGIFImage/SwiftGIFImage-Bridging-Header.h' does not exist"

I have messed around with the paths and the placement of SwiftGIFImage-Bridging-Header.h (and UIImage...h and UIImage...m), but it still is asking for your computer.

![screen shot 2015-05-05 at 15 39 27](https://cloud.githubusercontent.com/assets/12248126/7468591/1faaac2c-f33d-11e4-959c-7693cfbc7b00.png)

2) I also tried adding SwiftGIFImage-Bridging-Header.h and UIImage...and UIImage...m to my own project and calling UIImage.animatedImageWithAnimatedGIFData(imageData) (after loading with NSData(...)) but it complained that UIImage does not have a member named animatedImageWithAnimatedGIFData.

Thanks for your attention.
Adaza

**Comment by kiritmodi2702** [comment]
Yes it issue solve and upload new project temporary for Xcode 6.2. check http://ge.tt/5Z5sSqF2/v/0

**Comment by kiritmodi2702** [comment]
Now updated project Xcode 6.2.

**Comment by adaza** [comment]
Thanks so much for looking at this. I would love to get this working. I was unable to download the temporary project. 

I downloaded and ran the updated project. I get the same error with a different folder: Bridging Header '/Users/nimblechapps/Downloads/GIF...Bridging-Header.h' does not exist.

![screen shot 2015-05-07 at 11 19 08](https://cloud.githubusercontent.com/assets/12248126/7507976/0123d002-f4ab-11e4-881c-ba962d13aa36.png)

I am running Xcode 6.2 on 10.9.5 (I have not yet upgraded because of discoveryd) Is that likely to be the issue?

Thanks again,
Adaza

**Comment by adaza** [comment]
After I edited the paths of SWIFT_OBJC_BRIDGING_HEADER in SwiftGIFImage.xcodeproj, (with BBEDit, I can't figure out where it is in Xcode), it compiled and ran.

It doesn't display the image though. It throws this error.
May  7 13:48:40 bogon SwiftGIFImage[18837] <Error>: ImageIO: CGImageSourceCreateWithURL CFURLCreateDataAndPropertiesFromResource failed with error code -14.

I will continue messing with it, but let please me know if you have ideas.

**Comment by adaza** [comment]
The only thing I can find on the internet about error code 14 is general file corruption. I will try to find a better network situation. The only http servers I have good access to are quite geographically far from me.

Update: With "file:///Users...image.gif" it works! 

Question: Why does NSData(contentsOfUrl: "http://..." ) retrieve a good file but CGImageSourceCreateWithURL("http://...") --to the same file-- does not?

On a side note. I have noted that I don't seem to be able to put a gif in the Images.xcassets. Is there a trick to it?

**Comment by adaza** [comment]
In summary: I am happy now. Thanks so much. 

This works:
let url = NSURL(string: "http://....gif")
let imageData = NSData(contentsOfURL: url)
ImageGIF.image = UIImage.animatedImageWithAnimatedGIFData(imageData)

This doesn't work with my http network situation:
ImageGIF.image = UIImage.animatedImageWithAnimatedGIFURL(url)
responds with above error code -14

**Comment by adaza** [comment]
Also, it is odd that I had to edit the paths of SWIFT_OBJC_BRIDGING_HEADER in SwiftGIFImage.xcodeproj to remove the reference to your computer. Something seems amiss with that.

**Comment by adaza** [comment]
For anyone who doesn't yet know how to make your own project recognize the bridge, here is what I've figured out.

After File>Add Files... the 3 files to the project, (doesn't seem to matter much where):

Click the project in the Navigator, then Build Settings > All.
In Apple LLVM 6.0 - Language - Modules > Enable Modules (C and Objective C)
Choose Yes in the project column.

In Swift Compiler - Code Generator > Objective C Bridging Header
Add the full path of SwiftGIFImage-Bridging-Header.h in the Application column, and it fills it in the others: Resolved, Debug and Release.

It is strange that the full path of the bridging header is hard coded into the project. I have found that moving the project within my file structure causes the project to lose the header. Seems like Xcode should have a better system.

Thanks again. This is great!

**Comment by sentiasa** [comment]
I am unable to run the Demo (and the one @kiritmodi2702 linked here), because I have the bridging header error and it seems my path is also seems hard-coded, too: `bridging header '/Users/nimblechapps/Downloads/GIFIamgeView_Swift-master 2/SwiftGIFImage/SwiftGIFImage-Bridging-Header.h' does not exist.`

@adaza Have you been able to solve the issue? I tried opening the project with Sublime Text, but I don't understand what to edit :/ it seems like this in Sublime Text:

<blockquote class="imgur-embed-pub" lang="en" data-id="hIAYM7b"><a href="//imgur.com/hIAYM7b">View post on imgur.com</a></blockquote><script async src="//s.imgur.com/min/embed.js" charset="utf-8"></script>

My structure is
- SwiftGIFImage
  - UIImage+animatedGIF.h & .m
  - SwiftGIFImage
    - Bridging Header..

and in Swift Compiler - Objective-C Bridging Header -> SwiftGIFImage-Bridging-Header.h

but same error... :/

**Comment by sentiasa** [comment]
Fixed it :)) Thanks a lot.. I opened the project file with Sublime Text and edited all `Users/...../Bridging-Header.h parts..`

**Comment by kiritmodi2702** [comment]
See this one, if you have issue about bridging :
http://iosdevcenters.blogspot.com/2015/12/how-to-calling-objective-c-code-in-swift.html

**Comment by adaza** [comment]
I guess I should close this issue.

Today I have the question: If you have an animated gif in Images.xcassets, how can you display it? Anyone have ideas?
